# Generated by Django 5.0 on 2023-12-06 21:04

import django.db.models.deletion
import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='./default/placeholder.webp', max_length=10000, upload_to=index.models.Carousel.image_upload_to)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Upload images for carousel',
                'db_table': 'Images_Carousel',
            },
        ),
        migrations.CreateModel(
            name='ImageCarouselSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(default='', help_text='Select your images for see in the carousel', on_delete=django.db.models.deletion.CASCADE, to='index.carousel', validators=[index.models.ImageCarouselSelect.validate_image_count])),
            ],
            options={
                'verbose_name_plural': 'Select images for carousel',
            },
        ),
    ]
