# Generated by Django 5.0 on 2023-12-07 16:03

import django.db.models.deletion
import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        ('products', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ForeignKey(default='', help_text='Select a product to post in the carousel', on_delete=django.db.models.deletion.CASCADE, to='products.product', validators=[index.models.Carousel.validate_image_count]),
        ),
    ]
