# Generated by Django 5.0 on 2023-12-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_carousel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='image',
            new_name='series',
        ),
    ]
