# Generated by Django 5.0 on 2023-12-07 00:35

import django.db.models.deletion
import products.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', tinymce.models.HTMLField(default='')),
                ('brand', models.CharField(default='', max_length=200, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('offer_price', models.IntegerField(blank=True, default=0)),
                ('old_price', models.IntegerField(blank=True, default=0)),
                ('percentage', models.CharField(blank=True, default='', max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(default='./default/placeholder.webp', max_length=5000, upload_to=products.models.Product.image_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(default='', help_text='Select the category to which this product belongs', on_delete=django.db.models.deletion.CASCADE, to='categories.categories')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
