# Generated by Django 5.0 on 2023-12-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_brand_reviewproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_applied',
            field=models.BooleanField(default=False),
        ),
    ]
